import type { Metadata } from "next";
import { Major_Mono_Display, Sedan_SC, Junge } from 'next/font/google';
import "./globals.css";
import Footer from "./component/shared/Footer";
import Navbar from "./component/shared/Navbar";
import Script from "next/script";
import { Toaster } from "react-hot-toast";

export const majorMono = Major_Mono_Display({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-heading',
});

export const sen = Sedan_SC({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-body',
});

export const junge = Junge({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-accent',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${junge.variable} ${majorMono.variable} ${sen.variable} antialiased scroll-smooth`}
      >
        <Navbar></Navbar>

        <Script
          src="https://unpkg.com/@lottiefiles/dotlottie-wc@0.8.1/dist/dotlottie-wc.js"
          strategy="beforeInteractive"
          type="module"
        />



          <div className="min-h-screen ">
            {children}
            <Toaster position="top-center" reverseOrder={false} />

          </div>

          <Footer></Footer>
      </body>
    </html>
  );
}
